name: Daily data ingestion

on:
  schedule:
    - cron: "0 3 * * *"   # Tous les jours à 03:00 UTC
  workflow_dispatch:     # Permet de lancer à la main

jobs:
  ingestion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull ingestion image
        run: |
          docker pull antoninsanzv/data_gouv_ingestion:latest

      - name: Run ingestion
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            antoninsanzv/data_gouv_ingestion:latest
