name: Daily data ingestion

on:
  schedule:
    - cron: "0 3 * * *"   
  workflow_dispatch:     

jobs:
  ingestion:
    runs-on: ubuntu-latest

    steps:
      
      - name: Pull ingestion image
        run: |
          docker pull antoninsanzv/data_gouv_ingestion:latest

      - name: Run ingestion
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            antoninsanzv/data_gouv_ingestion:latest
